# Basic
title: GcsSloop
subtitle: Just do IT later.
welcome_message: 欢迎来到我的世界! 
description: 嗨，我是张泽帅！
creator: <a href="https://zzs-github.github.io">@zzs</a>

url: "https://zzs-github.github.io"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: GitHub,     in_site: false,  description: My GitHub,    url: 'https://github.com/ZZS-GitHub'}
    - {title: 目录,        in_site: true,  description: 博客目录,               url: '/timeline'}
    - {title: 关于,        in_site: true,  description: 关于作者 ,       url: '/info/about'}
    


plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: GcsSloop
    # duoshuo:
# Social
social:
    weibo: 5543154873
    github: ZZS-GitHub
    rss: /feed.xml
    mail: 2236880913@QQ.com
    copyright: http://choosealicense.online

# Google Analytics
ga:
    id: UA-82493667-1
    host: zzs-github.github.io
